# IQRF Gateway for Docker

version: '3'

services:
  daemon:
    image: iqrftech/iqrf-gateway-daemon:latest
    volumes:
      - /etc/iqrf-gateway-daemon
    ports:
      - "1338:1338"
      - "55000/udp:55000/udp" 
      - "55300/udp:55300/udp"
    restart: always

  webapp:
    depends_on:
      - daemon
    image: iqrftech/iqrf-gateway-webapp:latest
    volumes_from:
      - daemon
    ports:
      - "80:80"
    restart: always
