# IQRF Gateway for Docker

version: '3'

services:
  daemon:
    depends_on:
      - mosquitto
    image: iqrftech/iqrf-gateway-daemon:latest-amd64
    privileged: true
    volumes:
      - config-data:/etc/iqrf-gateway-daemon
    hostname: iqrf-gateway-daemon
    networks:
      - iqrf-network
    links:
      - mosquitto  
    ports:
      - "1338:1338"
      - "55000:55000/udp" 
      - "55300:55300/udp"
    expose:
      - "1338"
    devices:
      - "/dev/spidev2.0:/dev/spidev2.0"
    restart: always

  webapp:
    depends_on:
      - daemon
    image: iqrftech/iqrf-gateway-webapp:latest-amd64
    volumes:
      - config-data:/etc/iqrf-gateway-daemon
    hostname: iqrf-gateway-webapp
    networks:
      iqrf-network:
        aliases:
            - iqrf-gateway-webapp
    links:
      - daemon
    ports:
      - "8080:8080"
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    networks:
      iqrf-network:
        aliases:
            - mosquitto

volumes:
  config-data:

networks:
  iqrf-network:
    driver: "bridge"
